atilo: atilo.c File Reference
atilo.c File Reference
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Macros
#define __MAIN__
Functions
gint main_wnd_resized (GtkWidget *widget, GdkEventConfigure *event)
TBD.
void clear_hist_list (void)
TBD.
gint main_wnd_expose (GtkWidget *widget, GdkEventExpose *event)
TBD.
void create_hist_list (void)
TBD.
void init_new_game (const int f_draw, const int f_reset_history)
TBD.
int main (int argc, char *argv[])
TBD.
Detailed Description
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Definition in file atilo.c.
Macro Definition Documentation
#define __MAIN__
Definition at line 24 of file atilo.c.
Function Documentation
gint main_wnd_resized (GtkWidget * widget, GdkEventConfigure * event)
TBD.
Parameters
widget TBD
event TBD
Returns
BD
Definition at line 149 of file atilo.c.
References main_wnd.
void clear_hist_list (void)
TBD.
Definition at line 159 of file atilo.c.
References hist_list.
Referenced by init_new_game().
gint main_wnd_expose (GtkWidget * widget, GdkEventExpose * event)
TBD.
Parameters
widget TBD
event TBD
Returns
TBD
Definition at line 174 of file atilo.c.
References compute_size_elements_board(), draw_board(), and expose_init().
void create_hist_list (void)
TBD.
Definition at line 191 of file atilo.c.
References hist_list, main_hbox, RANDOM, and select_hist_handler_id.
void init_new_game (const int f_draw, const int f_reset_history)
TBD.
Parameters
f_draw TBD
f_reset_history TBD
Definition at line 269 of file atilo.c.
References board, board_drawing_area, clear_hist_list(), CODE_AROUND, CODE_BLACK, code_computer, CODE_EMPTY, code_human, CODE_WHITE, color_to_play, compute_nb_pawns(), computer_infos_msg(), ctime_black, ctime_white, enable_SaveGame(), player_infos_msg(), redraw_board(), show_horo(), show_poss_play_cursor(), t_start, and XY.
Referenced by main(), and on_New_game_activate().
int main (int argc, char * argv[])
TBD.
Parameters
argc TBD
argv TBD
Returns
TBD
Definition at line 325 of file atilo.c.
References create_layout(), init_new_game(), load_config(), and scan_fonts().