atilo: config.h File Reference
config.h File Reference
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Functions
void scan_fonts (void)
TBD.
char * find_max_font (const int width, const int height)
TBD.
int load_config (void)
TBD.
void save_config (void)
TBD.
Detailed Description
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Definition in file config.h.
Function Documentation
void scan_fonts (void)
TBD.
Definition at line 116 of file config.c.
References FONT_INFO::height, FONT_INFO::name, and FONT_INFO::width.
Referenced by main().
char* find_max_font (const int width, const int height)
TBD.
Parameters
width TBD
height TBD
Returns
TBD
Definition at line 173 of file config.c.
References FONT_INFO::height, FONT_INFO::name, and FONT_INFO::width.
Referenced by compute_size_elements_board(), and redraw_board().
int load_config (void)
TBD.
Returns
FALSE if needs to reload all fonts
Definition at line 197 of file config.c.
References config, CONFIG::level, LEVEL2, CONFIG::mainwnd_h, CONFIG::mainwnd_w, CONFIG::strategy, and STRATEGY4.
Referenced by main().
void save_config (void)
TBD.
Definition at line 229 of file config.c.
References config.