atilo: game.h File Reference
game.h File Reference
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Functions
int max_level_depth (void)
TBD.
void do_game (const unsigned char the_player, const unsigned char the_enemy, WHERE_TO_PLAY *where_to_play)
TBD.
Detailed Description
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Definition in file game.h.
Function Documentation
int max_level_depth (void)
TBD.
Returns
TBD
Definition at line 16 of file game.c.
References config, CONFIG::level, MAX_LEVELS, MAX_STRATEGIES, and CONFIG::strategy.
Referenced by do_game().
void do_game (const unsigned char the_player, const unsigned char the_enemy, WHERE_TO_PLAY * where_to_play)
TBD.
Parameters
the_player TBD
the_enemy TBD
where_to_play
Definition at line 327 of file game.c.
References board, chosen_move, WHERE_TO_PLAY::cnt, cnt, CODE_BLACK, CODE_WHITE, WHERE_TO_PLAY::elapsed, max_depth, max_level_depth(), nb_pawns, possib, WHERE_TO_PLAY::x, and WHERE_TO_PLAY::y.
Referenced by computer_play().