atilo: layout.c File Reference
layout.c File Reference
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Functions
void install_key_press_handler (const int enable)
TBD.
void install_motion_handler (const int enable)
TBD.
void expose_init (void)
TBD.
void compute_size_elements_board (void)
TBD.
void draw_pawn (GdkDrawable *drawable, const int r, const int c, const int pawn)
TBD.
void redraw_board (void)
TBD.
void draw_board (GdkDrawable *drawable)
TBD.
void create_layout (void)
TBD.
void computer_infos_msg (const char *fmt,...)
TBD.
void player_infos_msg (const char *fmt,...)
TBD.
Detailed Description
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Definition in file layout.c.
Function Documentation
void install_key_press_handler (const int enable)
TBD.
Parameters
enable TBD
Definition at line 74 of file layout.c.
References main_wnd.
void install_motion_handler (const int enable)
TBD.
Parameters
enable TBD
Definition at line 98 of file layout.c.
References board_drawing_area, and main_wnd_motion().
Referenced by computer_play().
void expose_init (void)
TBD.
Definition at line 174 of file layout.c.
References penBlackCell, and penWhiteCell.
Referenced by main_wnd_expose().
void compute_size_elements_board (void)
TBD.
Definition at line 189 of file layout.c.
References board_drawing_area, board_height, BOARD_HEIGHT_FENCE, board_width, BOARD_WIDTH_FENCE, board_xstart, board_ystart, cell_height, cell_width, find_max_font(), hist_list, and main_hbox.
Referenced by main_wnd_expose().
void draw_pawn (GdkDrawable * drawable, const int r, const int c, const int pawn)
TBD.
Parameters
drawable TBD
r TBD
c TBD
pawn TBD
Returns
TBD
Definition at line 245 of file layout.c.
References board_xstart, board_ystart, cell_height, CELL_HEIGHT_FENCE, cell_width, CELL_WIDTH_FENCE, CODE_BLACK, CODE_EMPTY, penBlackCell, and penWhiteCell.
Referenced by main_wnd_press(), main_wnd_release(), and redraw_board().
void redraw_board (void)
TBD.
Definition at line 262 of file layout.c.
References board, board_drawing_area, board_xstart, board_ystart, cell_height, cell_width, draw_pawn(), find_max_font(), penBlackCell, and XY.
Referenced by computer_turn(), draw_board(), and init_new_game().
void draw_board (GdkDrawable * drawable)
TBD.
Parameters
drawable TBD
Definition at line 322 of file layout.c.
References board_height, board_width, board_xstart, board_ystart, cell_height, cell_width, and redraw_board().
Referenced by main_wnd_expose().
void create_layout (void)
TBD.
Definition at line 434 of file layout.c.
References config, create_main_menu(), main_hbox, main_wnd, CONFIG::mainwnd_h, and CONFIG::mainwnd_w.
Referenced by main().
void computer_infos_msg (const char * fmt, ...)
TBD.
Parameters
fmt TBD
... TBD
Definition at line 480 of file layout.c.
Referenced by change_side(), computer_play(), init_new_game(), main_wnd_press(), and suggest_move().
void player_infos_msg (const char * fmt, ...)
TBD.
Parameters
fmt TBD
... TBD
Returns
TBD
Definition at line 499 of file layout.c.
Referenced by change_side(), computer_play(), computer_turn(), init_new_game(), and main_wnd_press().