atilo: menu.c File Reference
menu.c File Reference
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Functions
void on_New_game_activate (GtkWidget *w, gpointer data)
TBD.
void on_Save_game_activate (GtkWidget *w, gpointer data)
TBD.
void on_Load_game_activate (GtkWidget *w, gpointer data)
TBD.
void on_Edit_game_activate (GtkWidget *w, gpointer data)
TBD.
void on_Quit_activate (GtkWidget *w, gpointer data)
TBD.
void on_Change_side_activate (GtkWidget *w, gpointer data)
TBD.
void on_SuggestMove_activate (GtkWidget *w, gpointer data)
TBD.
void on_Settings_activate (GtkWidget *w, gpointer data)
TBD.
void on_Rules_of_Reversi_activate (GtkWidget *w, gpointer data)
TBD.
void on_About_atilo_activate (GtkWidget *w, gpointer data)
TBD.
void enable_NewGame (const int flag)
TBD.
void enable_SaveGame (const int flag)
TBD.
void enable_ChangeSide (const int flag)
TBD.
void enable_SuggestMove (const int flag)
TBD.
void create_main_menu (GtkWidget *vbox)
TBD.
Detailed Description
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Definition in file menu.c.
Function Documentation
void on_New_game_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 22 of file menu.c.
References init_new_game().
Referenced by create_main_menu().
void on_Save_game_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 32 of file menu.c.
References file_save_game().
Referenced by create_main_menu().
void on_Load_game_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 42 of file menu.c.
References file_load_game().
Referenced by create_main_menu().
void on_Edit_game_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 52 of file menu.c.
References warning_msg().
Referenced by create_main_menu().
void on_Quit_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 62 of file menu.c.
References main_wnd.
Referenced by create_main_menu().
void on_Change_side_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 72 of file menu.c.
References change_side().
Referenced by create_main_menu().
void on_SuggestMove_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 82 of file menu.c.
References suggest_move().
Referenced by create_main_menu().
void on_Settings_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 92 of file menu.c.
References dialog_settings().
Referenced by create_main_menu().
void on_Rules_of_Reversi_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 102 of file menu.c.
References main_wnd.
Referenced by create_main_menu().
void on_About_atilo_activate (GtkWidget * w, gpointer data)
TBD.
Parameters
w TBD
data TBD
Definition at line 117 of file menu.c.
References main_wnd, and VERSION.
Referenced by create_main_menu().
void enable_NewGame (const int flag)
TBD.
Parameters
flag TBD
Definition at line 136 of file menu.c.
void enable_SaveGame (const int flag)
TBD.
Parameters
flag TBD
Definition at line 145 of file menu.c.
Referenced by init_new_game(), and main_wnd_press().
void enable_ChangeSide (const int flag)
TBD.
Parameters
flag TBD
Definition at line 154 of file menu.c.
void enable_SuggestMove (const int flag)
TBD.
Parameters
flag TBD
Definition at line 163 of file menu.c.
void create_main_menu (GtkWidget * vbox)
TBD.
Parameters
vbox TBD
Definition at line 172 of file menu.c.
References main_wnd, on_About_atilo_activate(), on_Change_side_activate(), on_Edit_game_activate(), on_Load_game_activate(), on_New_game_activate(), on_Quit_activate(), on_Rules_of_Reversi_activate(), on_Save_game_activate(), on_Settings_activate(), and on_SuggestMove_activate().
Referenced by create_layout().