atilo: play.c File Reference
play.c File Reference
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Macros
#define CHECK_DIR(dir_offs)
#define CHECK_DIR(dir_offs)
Functions
char * lib_colors (const int n)
TBD.
void compute_nb_pawns (const int show)
TBD.
int do_build_possib (PCELL *ptr, const int cplayer, const int cenemy)
TBD.
int do_nb_possib (const int cplayer, const int cenemy)
TBD.
int show_poss_play_cursor (const unsigned char cplayer, const unsigned char cenemy)
Check each cell.
gint main_wnd_motion (GtkWidget *signal_widget, GdkEventMotion *event, gpointer data)
TBD.
int main_wnd_press (GtkWidget *signal_widget, GdkEventButton *event, gpointer data)
TBD.
int main_wnd_release (GtkWidget *signal_widget, GdkEvent *event, gpointer data)
TBD.
void computer_turn (void)
TBD.
void computer_play (WHERE_TO_PLAY *where_to_play, const unsigned char the_player, const unsigned char the_enemy, const int f_suggest)
TBD.
void suggest_move (void)
TBD.
void change_side (void)
TBD.
Detailed Description
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Definition in file play.c.
Macro Definition Documentation
#define CHECK_DIR (dir_offs)
Value:
\
    /* How many contigues enemies ? */ \
    for ( pscan = pcell, enemy_cnt = 0; ; enemy_cnt++ ) \
        if ( (c = *(pscan += dir_offs)) != cenemy ) \
            break; \
\
    /* At least one contigue enemy and last pawn is the player */ \
    if ( (enemy_cnt) && (c == cplayer) ) \
    { \
\
        /* Cumulate the nb of pawns took */ \
        nb_took += enemy_cnt; \
\
        /* Record all the enclosed enemy pawns */ \
        for ( n = enemy_cnt; n; n-- ) \
        { \
            pscan -= dir_offs; \
            *p++ = pscan; \
        } \
\
    }                           /* if */
Definition at line 137 of file play.c.
Referenced by do_build_possib(), and do_nb_possib().
#define CHECK_DIR (dir_offs)
Value:
\
    /* How many contigues enemies ? */ \
    for ( pscan = pcell, enemy_cnt = 0; ; enemy_cnt++ ) \
        if ( (c = *(pscan += dir_offs)) != cenemy ) \
            break; \
\
    /* At least one contigue enemy and last pawn is the player */ \
    if ( (enemy_cnt != 0) && (c == cplayer) ) \
        { \
\
        /* Cumulate the nb of pawns took */ \
        nb_took += enemy_cnt; \
\
        }                       /* if */
Definition at line 137 of file play.c.
Function Documentation
char* lib_colors (const int n) inline
TBD.
Parameters
n TBD
Returns
TBD
Definition at line 17 of file play.c.
Referenced by computer_turn(), and main_wnd_press().
void compute_nb_pawns (const int show)
TBD.
Parameters
show TBD
Definition at line 33 of file play.c.
References board, CODE_BLACK, CODE_WHITE, nb_pawns, show_nb_pawns(), and XY.
Referenced by computer_turn(), init_new_game(), and main_wnd_press().
int do_build_possib (PCELL * ptr, const int cplayer, const int cenemy) inline
TBD.
Parameters
ptr TBD
cplayer TBD
cenemy TBD
Returns
TBD
Definition at line 81 of file play.c.
References board, and CHECK_DIR.
Referenced by computer_turn(), main_wnd_press(), and show_poss_play_cursor().
int do_nb_possib (const int cplayer, const int cenemy) inline
TBD.
Parameters
cplayer TBD
cenemy TBD
Returns
TBD
Definition at line 160 of file play.c.
References board, and CHECK_DIR.
Referenced by _ponderation4().
int show_poss_play_cursor (const unsigned char cplayer, const unsigned char cenemy)
Check each cell.
If player can play, then change the cursor shape (ok). Else change also the cursor shape (nok). A local possibilities stack is used.
Parameters
cplayer TBD
cenemy TBD
Returns
TBD
Definition at line 224 of file play.c.
References board, do_build_possib(), possib, state_selectable, which_show_poss, and XY.
Referenced by change_side(), computer_turn(), init_new_game(), and main_wnd_press().
gint main_wnd_motion (GtkWidget * signal_widget, GdkEventMotion * event, gpointer data)
TBD.
Parameters
signal_widget TBD
event TBD
data TBD
Returns
TBD
Definition at line 269 of file play.c.
References board_xstart, board_ystart, cell_height, cell_width, and state_selectable.
Referenced by install_motion_handler().
int main_wnd_press (GtkWidget * signal_widget, GdkEventButton * event, gpointer data)
TBD.
Parameters
signal_widget TBD
event TBD
data TBD
Returns
TBD
Definition at line 306 of file play.c.
References board, board_drawing_area, board_xstart, board_ystart, cancel_last_human_move, cell_height, cell_width, cnt, CODE_BLACK, code_computer, code_human, color_to_play, compute_nb_pawns(), computer_infos_msg(), computer_turn(), ctime_black, ctime_white, do_build_possib(), draw_pawn(), enable_SaveGame(), hist_list, lib_colors(), player_infos_msg(), possib, select_hist_handler_id, show_horo(), show_poss_play_cursor(), t_start, which_show_poss, and XY.
int main_wnd_release (GtkWidget * signal_widget, GdkEvent * event, gpointer data)
TBD.
Parameters
signal_widget TBD
event TBD
data TBD
Returns
TBD
Definition at line 458 of file play.c.
References board_drawing_area, code_computer, CODE_EMPTY, and draw_pawn().
void computer_turn (void)
TBD.
Definition at line 473 of file play.c.
References board, cnt, CODE_BLACK, code_computer, code_human, color_to_play, compute_nb_pawns(), computer_play(), computer_turn(), ctime_black, ctime_white, do_build_possib(), hist_list, lib_colors(), player_infos_msg(), possib, redraw_board(), select_hist_handler_id, set_progressbar(), show_horo(), show_poss_play_cursor(), t_start, warning_msg(), WHERE_TO_PLAY::x, XY, and WHERE_TO_PLAY::y.
Referenced by change_side(), computer_turn(), and main_wnd_press().
void computer_play (WHERE_TO_PLAY * where_to_play, const unsigned char the_player, const unsigned char the_enemy, const int f_suggest)
TBD.
Parameters
where_to_play TBD
the_player TBD
the_enemy TBD
f_suggest TBD
Definition at line 602 of file play.c.
References board_drawing_area, WHERE_TO_PLAY::cnt, CODE_BLACK, code_computer, CODE_WHITE, computer_infos_msg(), config, do_end_game(), do_game(), WHERE_TO_PLAY::elapsed, install_motion_handler(), CONFIG::level, LEVEL1, LEVEL2, LEVEL3, LEVEL4, LEVEL5, main_wnd, nb_pawns, player_infos_msg(), WHERE_TO_PLAY::x, and WHERE_TO_PLAY::y.
Referenced by computer_turn(), and suggest_move().
void suggest_move (void)
TBD.
Definition at line 684 of file play.c.
References CODE_BLACK, CODE_WHITE, color_to_play, computer_infos_msg(), computer_play(), and set_progressbar().
Referenced by on_SuggestMove_activate().
void change_side (void)
TBD.
Definition at line 699 of file play.c.
References code_computer, code_human, color_to_play, computer_infos_msg(), computer_turn(), player_infos_msg(), set_owners(), show_nb_pawns(), and show_poss_play_cursor().
Referenced by on_Change_side_activate().