atilo: status.c File Reference
status.c File Reference
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Functions
void create_status (void)
TBD.
void set_progressbar (const int val, const int max_val)
TBD.
void show_nb_pawns (void)
TBD.
void set_owners (void)
TBD.
void show_horo (void)
TBD.
Variables
GtkAdjustment * progressadj
Detailed Description
Atilo: Othello/Reversi Game
Copyright (C) 1999-2007 Olivier Singla
http://atilo.sourceforge.net/
.
Definition in file status.c.
Function Documentation
void create_status (void)
TBD.
Definition at line 93 of file status.c.
References status_hbox.
void set_progressbar (const int val, const int max_val)
TBD.
Parameters
val TBD
max_val TBD
Returns
TBD
Definition at line 134 of file status.c.
Referenced by computer_turn(), and suggest_move().
void show_nb_pawns (void)
TBD.
Definition at line 144 of file status.c.
References CODE_BLACK, CODE_WHITE, and nb_pawns.
Referenced by change_side(), and compute_nb_pawns().
void set_owners (void)
TBD.
Definition at line 157 of file status.c.
References CODE_BLACK, code_computer, and CODE_WHITE.
Referenced by change_side().
void show_horo (void)
TBD.
Definition at line 165 of file status.c.
References ctime_black, and ctime_white.
Referenced by computer_turn(), init_new_game(), and main_wnd_press().
Variable Documentation
GtkAdjustment* progressadj
Definition at line 88 of file status.c.